### ISSUE TITLE
[FEATURE] 1.21 Support

### ISSUE THREAD

**Issue by BetaKors** [luavixen/damagenumbers#8]
Currently the game just crashes once a particle from the mod has to be loaded:

```java
[18:08:58] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.util.crash.CrashException: Rendering Particle
	at MC/net.minecraft.client.particle.ParticleManager.renderParticles(ParticleManager.java:457) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.WorldRenderer.handler$clg000$iris$renderOpaqueParticles(WorldRenderer.java:12198) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1033) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1087) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.GameRenderer.render(GameRenderer.java:850) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1285) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoSuchMethodError: net/minecraft/client/render/Tessellator.method_1349()Lnet/minecraft/client/render/BufferBuilder; (loaded from file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/Optimized%20Fabric%20(1.21)/.fabric/remappedJars/minecraft-1.21-0.15.11/client-intermediary.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@f7080e32) called from class dev.foxgirl.damagenumbers.client.TextParticle (loaded from file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/Optimized%20Fabric%20(1.21)/mods/damagenumbers-1.3.0-fabric.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@f7080e32).
	at dev.foxgirl.damagenumbers.client.TextParticle.buildGeometry(TextParticle.java:57) ~[damagenumbers-1.3.0-fabric.jar:?]
	at MC/net.minecraft.client.particle.ParticleManager.renderParticles(ParticleManager.java:451) ~[client-intermediary.jar:?]
	... 10 more
```

Notably I'm also using Iris, which as far as I know should work with this mod.

**Comment by luavixen** [comment]
This is expected, as Mojang made minor changes to some of the rendering APIs in the 1.21 update. Thank you for the report, I'll release a new version that fixes this issue quite soon.

Also thank you for such a nice deobfuscated stack trace! Are you using a mod that automatically deobfuscates/modifies stack traces for you? I appreciate the straightforwardness of your report.

**Comment by luavixen** [comment]
I have added support for Minecraft 1.21 in the latest update as part of https://github.com/luavixen/damagenumbers/commit/b77ee7071a54093849f4c6e0b72e055e0a9cf7f1. The updated version (v1.4.1) will soon be available once it is approved by Modrinth/CurseForge.
